Feature/elevator simple command
Team488/TeamXbot2018 pull request #14
Opened 2018-01-17 04:17 UTC by johnli01

This code includes:

Simple Elevator Commands
-Elevator moving up
-Elevator moving down
-Elevator stop
-Elevator move to Max Height
-Elevator move to Min Height

Simple Elevator Commands Test
-Test if Elevator moving up is actually moving up, and code won't break
-Test if Elevator moving down is actually moving down, and code won't break
-Test if Elevator stop is actually stopping, and code won't break
-Test if Elevator moving up to Max is actually moving up, and code won't break
-Test if Elevator moving down is actually moving down, and code won't break

2018-01-17 05:22 UTC, JohnGilb requested changes

2018-01-17 05:22 UTC, JohnGilb commented on CompetitionTemplate/src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
> +		motor.simpleSet(0.4);
Have this be controlled by a DoubleProperty

2018-01-17 05:22 UTC, JohnGilb commented on CompetitionTemplate/src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
> +		motor.simpleSet(-0.4);
Same as above

2018-01-17 05:22 UTC, JohnGilb commented on CompetitionTemplate/src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
> +		if (height >= maxHeight * 0.9) {
have these factors be a DoubleProperty

2018-01-17 05:22 UTC, JohnGilb commented on CompetitionTemplate/src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
> +	double maxHeight;
maxHeight and minHeight should be DoubleProperty instead of double.

2018-01-17 05:22 UTC, JohnGilb commented on CompetitionTemplate/src/main/java/competition/subsystems/elevator/commands/LowerCommand.java
> +	ElevatorSubsystem lower;
rename to elevator

2018-01-17 05:22 UTC, JohnGilb commented on CompetitionTemplate/src/main/java/competition/subsystems/elevator/commands/LowerCommand.java
> +
` log.info("Initializing") `

2018-01-17 05:22 UTC, JohnGilb commented on CompetitionTemplate/src/main/java/competition/subsystems/elevator/commands/MoveToMaxHeightCommand.java
> +	double max = 90;
We should ask the elevatorSubsystem what the max is - the command probably shouldn't know.

2018-01-17 05:22 UTC, JohnGilb commented on CompetitionTemplate/src/main/java/competition/subsystems/elevator/commands/MoveToMinHeightCommand.java
> +	double min = 0;
Same as in MoveToMaxHeightCommand

2018-01-17 05:22 UTC, JohnGilb commented on CompetitionTemplate/src/main/java/competition/subsystems/elevator/commands/RiseCommand.java
> +	ElevatorSubsystem rise;
rename to elevator

2018-01-17 05:22 UTC, JohnGilb commented on CompetitionTemplate/src/main/java/competition/subsystems/elevator/commands/RiseCommand.java
> +		// TODO Auto-generated method stub
` log.info("Initializing") `

2018-01-17 05:22 UTC, JohnGilb commented on CompetitionTemplate/src/main/java/competition/subsystems/elevator/commands/StopCommand.java
> +public class StopCommand extends BaseSubsystem {
should extend BaseCommand.

2018-01-17 05:22 UTC, JohnGilb commented on CompetitionTemplate/src/main/java/competition/subsystems/elevator/commands/StopCommand.java
> +		power = 0;
Doesn't actually do anything.

2018-01-17 05:22 UTC, JohnGilb commented on CompetitionTemplate/src/test/java/competition/subsystems/elevator/commands/MoveToMaxHeightCommandTest.java
> +	}
Also needs a verifyMovingDown, and you also need to check isFinished

2018-01-17 05:22 UTC, JohnGilb commented on CompetitionTemplate/src/test/java/competition/subsystems/elevator/commands/MoveToMinHeightCommandTest.java
> +
See previous test

2018-01-17 05:22 UTC, JohnGilb commented on CompetitionTemplate/src/test/java/competition/subsystems/elevator/commands/RiseCommandTest.java
> +		// TODO Auto-generated method stub
Anytime you see this ` // TODO Auto-generated method stub ` you should delete it.

2018-01-17 05:22 UTC, JohnGilb commented on CompetitionTemplate/src/test/java/competition/subsystems/elevator/commands/StopCommandTest.java
> +
You need to have the elevator moving before this, otherwise you're not actually testing if this stops it.

2018-01-23 19:21 UTC, JohnGilb approved these changes

2018-01-23 19:21 UTC, merged

2018-02-07 05:59 UTC, WasabiFan commented
@JohnGilb There were a couple issues with this and subsequent PRs that are coming up in review now.

1. There are "magic numbers" all over, especially [here](https://github.com/Team488/TeamXbot2018/pull/14/files#diff-5da342919875fdf309d72547f3cfb549R135), which aren't properties nor are explained.
2. There are multiple independent copies of the same code which sets up a PID manager and then calls it. In the up-to-date branch, this means that five or so reasonably large commands are copies of each other with only different goals. We should have a setpoint system instead.