Feature/gripper intake
Team488/TeamXbot2018 pull request #24
Opened 2018-01-24 04:50 UTC by johnli01

Finished writing:
-GripperIntake commands
-GripperIntake Skeleton
-GripperIntake Tests

2018-01-24 20:40 UTC, JohnGilb requested changes

2018-01-24 20:40 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/gripperintake/GripperIntakeSubsystem.java
> +	public XDigitalInput calibrationSensor;
You're not using this, so remove it.

2018-01-24 20:40 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/gripperintake/GripperIntakeSubsystem.java
> +		rightMotor.configSelectedFeedbackSensor(FeedbackDevice.QuadEncoder, 0, 0);
Remove these lines for now - I don't think encoders are planned for these wheels.

2018-01-24 20:40 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/gripperintake/GripperIntakeSubsystem.java
> +	public void maxOut() {
rename to `eject()`

2018-01-24 20:40 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/gripperintake/GripperIntakeSubsystem.java
> +	public void maxIn() {
rename to `intake`

2018-01-24 20:40 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/gripperintake/GripperIntakeSubsystem.java
> +	public void halfRightIn() {
rename to `intakeRightDominant`

2018-01-24 20:40 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/gripperintake/GripperIntakeSubsystem.java
> +	public void halfLeftIn() {
rename to `intakeLeftDominant`

2018-01-24 20:40 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/gripperintake/commands/GripperInHalfLeft.java
> +public class GripperInHalfLeft extends BaseCommand {
all commands need to end with the word `Command`

2018-01-24 20:40 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/gripperintake/commands/GripperInHalfLeft.java
> +
remove blank lines

2018-01-24 20:40 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/gripperintake/commands/GripperInHalfRight.java
> +
just remove blank lines in functions most of the time

2018-01-25 00:12 UTC, johnli01 commented on Competition2018/src/main/java/competition/subsystems/gripperintake/GripperIntakeSubsystem.java
> +	public XDigitalInput calibrationSensor;
I think I shouldn't delete the public XCANTalon rightMotor and leftMotor because I use them in the methods later like leftMotor.simpleSet();

2018-01-25 21:13 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/gripperintake/GripperIntakeSubsystem.java
> +	public XDigitalInput calibrationSensor;
I mean the calibration sensor.

2018-01-25 21:21 UTC, JohnGilb requested changes

2018-01-25 21:21 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/gripperintake/GripperIntakeSubsystem.java
> +	 */
This comment isn't attached to anything. Did you used to have a `setPower(double power)` method here?

2018-01-25 21:21 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/gripperintake/commands/GripperEject.java
> +public class GripperEject extends BaseCommand {
All commands should end with the word command, e.g. `GripperEjectCommand`

2018-01-25 21:21 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/gripperintake/commands/GripperEject.java
> +		this.intake = intake;
you also need to require the subsystem.
`this.requires(intake)`

2018-01-25 21:21 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/gripperintake/commands/GripperIntake.java
> +public class GripperIntake extends BaseCommand {
All commands should end with the word command

2018-01-25 21:21 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/gripperintake/commands/GripperIntake.java
> +		this.intake = intake;
add requires

2018-01-25 21:21 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/gripperintake/commands/GripperLeftDominant.java
> +public class GripperLeftDominant extends BaseCommand {
All commands should end with the word command

2018-01-25 21:21 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/gripperintake/commands/GripperLeftDominant.java
> +		this.intake = intake;
requires

2018-01-25 21:21 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/gripperintake/commands/GripperRightDominant.java
> +public class GripperRightDominant extends BaseCommand {
All commands should end with the word command

2018-01-25 21:21 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/gripperintake/commands/GripperRightDominant.java
> +		this.intake = intake;
requires

2018-01-26 02:47 UTC, closed without merging