added current limit to motor
Team488/TeamXbot2018 pull request #66
Opened 2018-02-10 22:51 UTC by christiancruzfhs

2018-02-10 23:17 UTC, JohnGilb requested changes

2018-02-10 23:17 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
> +        peakCurrentLimit = propMan.createPersistentProperty("Peak current limit", 35);
`Elevator Peak Current Limit`

2018-02-10 23:17 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
> +        peakCurrentDuration = propMan.createPersistentProperty("Peak current duration", 200);
etc

2018-02-10 23:17 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
> +        continuousCurrentLimit = propMan.createPersistentProperty("Continuous current limit", 30);
etc

2018-02-10 23:17 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
> +        motor.configPeakCurrentLimit((int) peakCurrentLimit.get(), 0);
choose defaults that aren't 0, or this robot will never move.

2018-02-11 00:47 UTC, JohnGilb approved these changes

2018-02-13 22:43 UTC, WasabiFan commented on Competition2018/src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
> +    final BooleanProperty upperLimitSensor;
`private`

2018-02-13 22:43 UTC, WasabiFan commented on Competition2018/src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
> +        motor.configPeakCurrentLimit((int) elevatorPeakCurrentLimit.get(), 0);
Property changes will never be propagated to the Talon. Do we want to do something like @JohnGilb did for the drive?

2018-02-13 22:43 UTC, WasabiFan commented on Competition2018/src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
> +        motor.enableCurrentLimit(true);
Property/command/etc. to disable current limit if it causes trouble?

2018-02-14 02:45 UTC, JohnGilb requested changes
Do what Kaelin says =]

2018-02-14 03:42 UTC, JohnGilb approved these changes

2018-02-14 03:54 UTC, JohnGilb approved these changes

2018-02-14 04:06 UTC, merged