Feature/limit power near top bottom
Team488/TeamXbot2018 pull request #77
Opened 2018-02-14 04:32 UTC by martinnguyen1

2018-02-16 02:32 UTC, JohnGilb requested changes

2018-02-16 02:32 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
> +        if(getCurrentHeightInInches() < getHeightNearLowLimit()) {
All of this logic needs to be inside the `if (isCalibrated)` above.

2018-02-16 02:32 UTC, JohnGilb commented on Competition2018/src/test/java/competition/subsystems/elevator/commands/ControlElevatorViaJoystickCommandTest.java
> +        ((MockFTCGamepad) oi.operatorGamepad).setRightStick(new XYPair(0, 1));
remove this extra space

2018-02-16 02:32 UTC, JohnGilb commented on Competition2018/src/test/java/competition/subsystems/elevator/commands/ControlElevatorViaJoystickCommandTest.java
> +            double power = (double) i / 100;
remove the space so it's `(double)i / 100`

2018-02-16 02:47 UTC, WasabiFan commented on Competition2018/src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
> +        heightNearLowLimit = propMan.createPersistentProperty("Elevator Height Near Low Limit", 13);
Presumably we know the _total_ height of the elevator somewhere... could we change these properties to be a margin from the top/bottom rather than the total height?

2018-02-16 02:47 UTC, WasabiFan commented on Competition2018/src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
> +        powerNearLowLimit = propMan.createPersistentProperty("Max Power Near Low Limit", -0.3);
I'd suggest making these powers positive and then inverting them when used. I could probably mess up the system if I accidentally forgot the negative sign here.

2018-02-18 05:49 UTC, JohnGilb approved these changes

2018-02-18 05:58 UTC, merged