Feature/command group auto
Team488/TeamXbot2018 pull request #91
Opened 2018-02-17 21:00 UTC by johnli01

Drives straight, and shoots cube into scale/switch regardless of whos color it is

2018-02-17 23:59 UTC, johnli01 commented
Working on making Tests for them

2018-02-23 05:33 UTC, JohnGilb requested changes

2018-02-23 05:33 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/drive/DriveSubsystem.java
> +    public double leftTicksPerFiveFt() {
rename this to `getLeftTicksPerFiveFeet`

2018-02-23 05:33 UTC, JohnGilb commented on Competition2018/src/main/java/competition/subsystems/drive/DriveSubsystem.java
> +    public double rightTicksPerFiveFt() {
see above

2018-02-25 04:44 UTC, JohnGilb approved these changes

2018-02-25 04:49 UTC, merged